[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true

[buildPlans.IosevkaCustom.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifed-symmetric"
capital-q = "crossing"
i = "hooky"
l = "serifed-semi-tailed"
t = "flat-hook"
y = "straight-turn-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-ef = "split-serifless"
zero = "oval-dotted" # "oval-slashed-split"
two = "straight-neck-serifless"
five = "upright-flat-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
asterisk = "penta-low"
number-sign = "slanted"
at = "compact"
dollar = "open"
percent = "rings-continuous-slash"
# lig-ltgteq = "slanted"

[buildPlans.IosevkaCustom.variants.italic]
i = "tailed-serifed"
k = "straight-serifless"
l = "tailed-serifed"
t = "bent-hook"
y = "cursive-serifless"
cyrl-u = "cursive-serifless"

[buildPlans.IosevkaCustom.ligations]
inherits = "clike"
disables = ["plus-plus", "plus-plus-plus", "minus-minus", "minus-minus-minus", "eqeq", "eqeqeq"]

[buildPlans.IosevkaCustom.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCustom.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaCustom.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
